### ISSUE TITLE
Cherry leaves don't wave.

### ISSUE THREAD

**Issue by Gamerocker7000** [kolgushev/Pixel-Perfect-B#2] opened 2023-07-15 21:32 UTC
**Describe the bug**
Simply put, you forgot to make the cherry leaves wave in your shaderpack released for 1.20 when the option to make full blocks including leaves wave is on.

**To Reproduce**
1: Go to Settings, Extras, Weather, Wind, and enable "Waving full blocks"
2: Look at a cherry tree.

**Expected behavior**
I expect the Cherry Leaves to wave like every other type of leaves.

**Screenshots**

**Desktop (please complete the following information):**
 - Loader and loader version Additive 1.17.6 (Quilt), Iris 1.6.4
 - Minecraft version Minecraft 1.20.1
 - Graphics Card NVidia GTX 1060 3GB
 - OS: Windows 10

**Comment by kolgushev** [comment] 2023-07-16 19:12
Thanks for leaving a bug report - the issue should be fixed in [Pixel Perfect 1.3.4](https://modrinth.com/shader/pixel-perfect/version/1.3.4). Please reply with whether this release fixed it for you so I know whether to close the issue.

**Comment by kolgushev** [comment] 2023-07-19 00:31
I'll assume the issue is fixed and close this issue, please leave another bug report if this issue persists (or if you have a different bug).

**Closed by kolgushev** 2023-07-19 00:31 UTC
Labels: suggestion
